services:
    web:
        build: ./web
        depends_on:
            - database
            - cache
        environment:
            - DATABASE_URL=postgresql://postgres:password@database:5432/myapp
            - REDIS_URL=redis://cache:6379
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "8888:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
        networks:
            - app-network

    database:
        build: ./database
        environment:
            - POSTGRES_DB=myapp
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - app-network

    cache:
        build: ./cache
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
